baseURL = 'https://durre.net/'
languageCode = 'en-us'
title = '.hack//Durre'
theme = 'durre'

[params]
  description = 'a personal site'
  author = 'Durre'
  tagline = 'close this World / open the Next'

  [[params.friends]]
    name = 'Hugo'
    url  = 'https://gohugo.io'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
  [[menus.main]]
    name = 'Blog'
    pageRef = '/posts'
    weight = 30
  [[menus.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 40
